# Generated by Django 2.1.7 on 2019-03-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fibResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("nthFib", models.CharField(max_length=75)),
                ("time", models.CharField(max_length=50)),
            ],
            options={"db_table": "nthfib"},
        )
    ]
